### ISSUE TITLE
Automated way to install slack on Ubuntu

### ISSUE THREAD

**Issue by gibfahn** [gibfahn/dot#2]
This is my current script to automatically set up Slack on a new machine. However I heard from the Slack team that this isn't a reliable way to automatically download slack. I'm not sure what the right way would be.

https://github.com/gibfahn/dot/blob/cf97b6f2e4adb87b92ad27d7e0fd7e3a45a01eda/setup/ubu.sh#L105-L112

An alternative would be:

```bash
curl -o https://downloads.slack-edge.com/linux_releases/slack-desktop-2.7.1-amd64.deb
sudo dpkg -i slack-desktop-2.7.1-amd64.deb
sudo apt update && sudo apt upgrade -y
```

But this relies on the `2.7.1` image being there forever (and means you have to download an old version and then upgrade every time). Ideally there'd be a 

https://downloads.slack-edge.com/linux_releases/slack-desktop-latest-amd64.deb

like Google Chrome, which has:

https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

**Comment by gibfahn** [comment]
What I **don't** want to have to do is:

- Go to https://slack.com/downloads/linux
- Click `DOWNLOAD UBUNTU (64-BIT)`
- Manually run `dpkg`

**Comment by gibfahn** [comment]
This is apparently the recommended way to do it (recommended by Slack):

```bash
echo "deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main" | sudo tee /etc/apt/sources.list.d/slack.list >/dev/null
sudo apt install -y slack
```

**Comment by robhung** [comment]
> This is apparently the recommended way to do it (recommended by Slack):
> 
> ```shell
> echo "deb https://packagecloud.io/slacktechnologies/slack/debian/ jessie main" | sudo tee /etc/apt/sources.list.d/slack.list >/dev/null
> sudo apt install -y slack
> ```

Doesn't seem to work anymore?

> Get:10 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease [23.5 kB]
> Err:10 https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease
>   The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C6ABDCF64DB9A0B2
> Reading package lists... Done 
> W: GPG error: https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY C6ABDCF64DB9A0B2
> E: The repository 'https://packagecloud.io/slacktechnologies/slack/debian jessie InRelease' is not signed.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by gibfahn** [comment]
>Doesn't seem to work anymore?

I'm afraid I haven't had an Ubuntu machine recently so I'm not sure what the new solution is. Best bet is to email Slack support and ask if they have updated instructions. If they do let me know!

**Comment by neil92** [comment]
For anyone still having this issue, they have an updated, automated, install script on their [packagecloud](https://packagecloud.io/slacktechnologies/slack) site:
```
curl -s https://packagecloud.io/install/repositories/slacktechnologies/slack/script.deb.sh | sudo bash
```

If you prefer to update the sources and key manually, they have those instructions too:
https://packagecloud.io/slacktechnologies/slack/install#manual-deb
